### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by AdityaSrivast** [Awesome-React-Modules/React-Dark#13]
Add issue template for the project. 

Refer:
- https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository
- https://help.github.com/en/github/building-a-strong-community/manually-creating-a-single-issue-template-for-your-repository

**Comment by Aman-Codes** [comment]
@AdityaSrivast I am a GSSOC participant and I would like to add an issue template folder with bug report, feature request and pull request template. Please assign me this issue.
## Screenshots
### Bug report
![bug report](https://user-images.githubusercontent.com/54680709/77220483-80cd5d00-6b66-11ea-8685-2751fa20c0c2.PNG)

### Feature Request
![feature request](https://user-images.githubusercontent.com/54680709/77220495-98a4e100-6b66-11ea-8197-e72016d126c0.PNG)

### Pull Request
![pull request](https://user-images.githubusercontent.com/54680709/77220497-9c386800-6b66-11ea-9d0a-72820d72a239.PNG)

**Comment by AdityaSrivast** [comment]
Sure @Aman-Codes go ahead
