### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Aman-Codes** [Awesome-React-Modules/React-Dark#19]
**Is your feature request related to a problem? Please describe.**
No CODE_OF_CONDUCT.md file is present.

**Describe the solution you'd like**
@plxity  As a GSSOC participant I would like to add a CODE_OF_CONDUCT.md file in this project. Using [this]( https://www.contributor-covenant.org/version/1/4/code-of-conduct.html) as a reference. 

**Additional context**
### Screenshots

![code of conduct1](https://user-images.githubusercontent.com/54680709/77505634-beddc000-6e89-11ea-9dd5-f1e13ef6c6c9.PNG)
![code of conduct2](https://user-images.githubusercontent.com/54680709/77505638-c0a78380-6e89-11ea-8aa4-efcb21133da7.PNG)

**Comment by Kuljeet-123** [comment]
@yellowwoods12 Can I work on this issue??

**Comment by Aman-Codes** [comment]
@yellowwoods12 Sorry for the late response. I would like to know your email id where participants can report any acceptable behavior.

**Comment by yellowwoods12** [comment]
Hi @Aman-Codes, ping me on slack.

**Comment by Kuljeet-123** [comment]
@yellowwoods12 @plxity Please review it and merge it so that I can update the README also.
