### ISSUE TITLE
Add the link of Codepen implementation of the module in README.md

### ISSUE THREAD

**Issue by plxity** [Awesome-React-Modules/React-Dark#6]

**Comment by BhuwanChandra** [comment]
Hey, I would like to work on this.

**Comment by vipuldcoder** [comment]
I am interested with the issue.

**Comment by Kuljeet-123** [comment]
@plxity  can I take up this issue.

**Comment by plxity** [comment]
As @vipuldcoder has no updates on this. I am assigning this to  @Kuljeet-123

**Comment by Kuljeet-123** [comment]
@plxity  tysm for assigning me this.

**Comment by Kuljeet-123** [comment]
@plxity Please review my PR #10  and merge into the repo.
