### ISSUE TITLE
Make a document CONTRIBUTING.md

### ISSUE THREAD

**Issue by vipuldcoder** [Awesome-React-Modules/React-Dark#9]
Hello Everyone,
This is a new document that helps the open source contributors to understand and learn. How to get involved to contribute to this project. This makes a document helps us the collaborator to understand what this project is and how they can contribute towards it.

**Comment by AdityaSrivast** [comment]
@vipuldcoder go ahead :rocket:

**Comment by vipuldcoder** [comment]
I want to work on this issue.

**Comment by Kuljeet-123** [comment]
@vipuldcoder  @plxity  I would like to work on this issue.

**Comment by shreyakapoor08** [comment]
Can i take up this issue

**Comment by arpit9667** [comment]
This issue is already assigned to @vipuldcoder.

**Comment by vipul-aggarwal-099** [comment]
@shreyakapoor08 @Kuljeet-123 I really happy to give this issue to both of you and I want you both to work together and You need to have a daily Zoom meeting for atleast 1 hour and any one of them will report @me or @arpit9667 about your progress and If you have any issue, please do let me and @arpit9667 know. But I don't need any excuse and I want to work on this really seriously. If you still failed to meet, you can have a 10 minute meeting and if you need some help, you can schedule a call with the mentors for this project.  Good Luck 👍
